1

diff --git a/ElasticStack/init.d/logstash b/ElasticStack/init.d/logstash
--- a/ElasticStack/init.d/logstash
+++ b/ElasticStack/init.d/logstash
@@ -1,19 +1,32 @@
 ```
 #!/bin/bash
+
 # chkconfig: 345 20 80
+
 # description: logstash
+
 #
 ########################################################
 #
+
 #    脚本名称: logstash.sh
+
 #
+
 #    功    能: 启动、关停 服务
+
 #
+
 #    用    法: bash logstash.sh [<stop>|<start>|<restart>]
+
 #
+
 #    作    者: JerryHan
+
 #
+
 #    日    期: 2019/08/13
+
 #
 ########################################################
 #
@@ -31,25 +44,26 @@ _STOP(){
 
 case ${1} in
 
-    "start")
-        _START
-        ;;
-    
-    "stop")
-        _STOP
-        ;;
-    
-    "restart")
-        _STOP
-        sleep 2
-        _START
-        ;;
-    
-    "*"|"")
-        { echo "Invalid Parameter" 2>&1;exit 1; }
-        ;;
+"start")
+    _START
+    ;;
+
+"stop")
+    _STOP
+    ;;
+
+"restart")
+    _STOP
+    sleep 2
+    _START
+    ;;
+
+"*"|"")
+    { echo "Invalid Parameter" 2>&1;exit 1; }
+    ;;
 
 esac
 
 # (END)
 ```
+
